services:
  - type: web
    name: all-in-one-career-api
    env: docker
    plan: starter
    region: oregon
    branch: master
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_SECRET
        value: climbly_admin_secret_2024
        sync: false
